---
- name: playbook
  hosts:
    - host
  gather_facts: False

  tasks:
    - name: include role
      include_role:
        name: role
      vars:
        param: "{{item}}"
      with_items:
        - item1
        - item2
        - item3


